Exit if start is called and process is already running.

diff --git a/jobs/uaa/templates/uaa_ctl.erb b/jobs/uaa/templates/uaa_ctl.erb
--- a/jobs/uaa/templates/uaa_ctl.erb
+++ b/jobs/uaa/templates/uaa_ctl.erb
@@ -128,8 +128,8 @@ case $1 in
     then
       echo "[uaa-start] UAA not running according to pid_guard - proceeding with startup"
     else
-      echo "[uaa-start] UAA already running according to pid_guard- check successful...."
-      exit 0
+      echo "[uaa-start] UAA already running according to pid_guard - aborting start process"
+      exit 1
     fi
 
     echo "[uaa-start] About to starting UAA"
