Rewrite pre-start script
- Also change logging format for pre-start, post-start, and uaa scripts
to make them all consistent
- Remove some code from pre-start which copied tomcat and changed some
permissions because those things are not needed with bpm

[#165160019]

Signed-off-by: Andrew Wittrock <awittrock@pivotal.io>

diff --git a/jobs/uaa/templates/bin/post-start b/jobs/uaa/templates/bin/post-start
--- a/jobs/uaa/templates/bin/post-start
+++ b/jobs/uaa/templates/bin/post-start
@@ -1,6 +1,12 @@
 #!/bin/bash
 
-echo "uaa-post-start - starting at $(date)"
+set -euo pipefail
+
+function log {
+    echo "[$(date '+%Y-%m-%d %H:%M:%S').$(($(date +%N)/1000000))] uaa-post-start - $1"
+}
+
+log "Starting"
 
 TS_DIR=/var/vcap/data/uaa/post-start
 mkdir -p ${TS_DIR}
@@ -8,30 +14,28 @@ WHEN_FINISH=${TS_DIR}/when-finish.timestamp
 WHEN_NOW=${TS_DIR}/when-now.timestamp
 
 delete_ts_files() {
-  rm -f "${WHEN_FINISH}"
-  rm -f "${WHEN_NOW}"
-  echo "uaa-post-start - cleaned up timestamp files"
+    rm -f "${WHEN_FINISH}"
+    rm -f "${WHEN_NOW}"
+    log "Cleaned up timestamp files"
 }
 
 touch -d "10 minutes" "${WHEN_FINISH}" # this creates a file with a timestamp 10 minutes in the future
 touch "${WHEN_NOW}"
-EXPIRATION=$(ls -la --full-time "${WHEN_FINISH}" | awk '{print $6 " " $7}')
-echo "uaa-post-start - performing post start healthcheck until ${EXPIRATION}"
 
-# This is a timeout:
+log "Performing post start healthcheck until $(stat $WHEN_FINISH -c '%y')"
+
 # "-ot" is "older than"
 while [ "${WHEN_NOW}" -ot "${WHEN_FINISH}" ]; do
     /var/vcap/jobs/uaa/bin/health_check
     check=$?
     if [ "$check" -eq "0" ]
     then
-        echo "uaa-post-start - post start health check successful at $(date)"
+        log "Health check successful"
         delete_ts_files
         exit 0
     elif  [ "$check" == "2" ]
     then
-        echo "uaa-post-start - post start failed - server failed to start successfully at $(date)"
-        echo "check uaa.log to find out why the server failed to start"
+        log "FAILED: Server failed to start successfully. Check uaa.log to find out why the server failed to start."
         delete_ts_files
         exit 1
     fi
@@ -39,7 +43,6 @@ while [ "${WHEN_NOW}" -ot "${WHEN_FINISH}" ]; do
     touch "${WHEN_NOW}"
 done
 
-echo "uaa-post-start - post start health check failed - timeout at $(date)"
-echo "check uaa.log to find out why the server failed to start"
+log "FAILED: Health check failed. Timed out. Check uaa.log to find out why the server failed to start."
 delete_ts_files
 exit 1
