UAA writes cert bundle to a new location
Prior to this commit, the pre-start script used the
update-ca-certificates command to generate a cert bundle in a well known
location (/etc/ssl/certs/ca-certificates.crt).  Other jobs may also be
trying to call update-ca-certificates to update the same cert bundle.
Unfortunately, there's a period of time during the execution of
update-ca-certificates in which the certificate bundle is deleted from
the file system. UAA is not expecting the cert bundle to be missing and
errors out in unexpected ways.

Now, when UAA generates this bundle, it ensures the bundle is written to
a specially named file which cannot be removed by other jobs. This is
done via an undocumented flag. It's probably fine.

[#165159048]

Signed-off-by: Jeremy Morony <jmorony@pivotal.io>
Co-authored-by: Jeremy Morony <jmorony@pivotal.io>

diff --git a/jobs/uaa/templates/bin/uaa b/jobs/uaa/templates/bin/uaa
--- a/jobs/uaa/templates/bin/uaa
+++ b/jobs/uaa/templates/bin/uaa
@@ -46,7 +46,12 @@ function process_certs {
 
 echo "`date` [uaa] UAA Preparing Certs"
 CERT_FILE="/tmp/ca-certificates.crt"
-cp /etc/ssl/certs/ca-certificates.crt "$CERT_FILE"
+if [[ ! -f /etc/ssl/certs/uaa-ca-certificates.crt ]]; then
+  echo "/etc/ssl/certs/uaa-ca-certificates.crt should have been created by the pre-start script, but is missing. Exiting."
+  exit 1
+fi
+
+cp /etc/ssl/certs/uaa-ca-certificates.crt "$CERT_FILE"
 
 CONF_DIR="/var/vcap/jobs/uaa/config"
 CACHE_DIR="/var/vcap/data/uaa/cert-cache"
